DROP DATABASE IF EXISTS bamazonDB;
CREATE DATABASE bamazonDB;

USE bamazonDB;

CREATE TABLE inventory (
item_id INT NOT NULL AUTO_INCREMENT,
item_name VARCHAR 100 NOT NULL,
price INT NOT NULL,
quantity INT NOT NULL
PRIMARY KEY (item_id)

